# Chart Testing configuration for Helm charts
target-branch: main
chart-dirs:
  - helm
chart-repos:
  - jetstack=https://charts.jetstack.io
  - ingress-nginx=https://kubernetes.github.io/ingress-nginx
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: true
validate-chart-schema: true
validate-yaml: true