apiVersion: v2
name: grafana-observability
description: Custom Prometheus monitoring stack wrapper chart
type: application
version: 0.1.1
appVersion: "v0.83.0"

dependencies:
  - name: kube-prometheus-stack
    version: 76.1.0
    repository: https://prometheus-community.github.io/helm-charts
