# Default values for my-prom-stack
# This is a wrapper chart for kube-prometheus-stack

# All kube-prometheus-stack values are nested under this key
kube-prometheus-stack:
  # Override the default namespace if needed
  namespaceOverride: ""

  # Component enable/disable toggles
  alertmanager:
    enabled: true
  grafana:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: true
  coreDns:
    enabled: true
  kubeEtcd:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  prometheusOperator:
    enabled: true
  prometheus:
    enabled: true

  # Grafana configuration (when enabled)
  grafana:
    enabled: true
    service:
      type: ClusterIP
      port: 80

    # Admin credentials - use existing secret or auto-generate
    # adminPassword: "prom-operator"  # REMOVED: Security risk - use admin.existingSecret instead
    admin:
      existingSecret: "grafana-admin-secret"
      userKey: admin-user
      passwordKey: admin-password

    # Resource limits and requests
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

    # Health checks
    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    # Persistence configuration
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: "local-path"  # Change to your preferred storage class
      accessModes:
        - ReadWriteOnce

    # Default ingress configuration (disabled)
    ingress:
      enabled: false

  # Prometheus configuration (when enabled)
  prometheus:
    enabled: true
    service:
      type: ClusterIP
      port: 9090

    # Storage configuration
    prometheusSpec:
      # Resource limits and requests
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 1Gi

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi

  # AlertManager configuration (when enabled)
  alertmanager:
    enabled: true
    service:
      type: ClusterIP
      port: 9093

    # Storage configuration
    alertmanagerSpec:
      # Resource limits and requests
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi

      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi

# Custom additional configurations can be added here
# without needing to modify the upstream chart
