{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.n8n.database.type "postgresdb" }}
  db-password: {{ .Values.n8n.database.password | b64enc | quote }}
  db-user: {{ .Values.n8n.database.username | b64enc | quote }}
  db-host: {{ .Values.n8n.database.host | b64enc | quote }}
  db-port: {{ .Values.n8n.database.port | b64enc | quote }}
  db-database: {{ .Values.n8n.database.database | b64enc | quote }}
  {{- end }}
{{- end }}
