apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.n8n.database.type "postgresdb" }}
  db-password: {{ .Values.n8n.database.password | b64enc | quote }}
  {{- end }}
