apiVersion: v2
name: ingress-nginx
description: Wrapper chart for ingress-nginx controller with custom configurations and best practices
type: application
version: 0.1.0
appVersion: "1.13.0"

keywords:
  - ingress
  - nginx
  - kubernetes
  - reverse-proxy
  - load-balancer

dependencies:
  - name: ingress-nginx
    version: 4.13.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
