n8n:
  webhookUrl: "http://n8n.local:$NODE_PORT"
  timezone: "America/WEST.^-^"

service:
  type: NodePort
  nodePort: 31564

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "500m"

postgresql:
  enabled: false
